OpenSCAP/scap-workbench

CMakeLists.txt

Only minimal changes to the build process required.

Switch to QT5

---

README.md

Preview: https://github.com/ybznek/scap-workbench/blob/v1-1-readme/README.md

Fix root commands highlight in README.md

---

src/SSGIntegrationDialog.cpp
ui/SSGIntegrationDialog.ui

The pullrequest:
- Add scrollbar
- Make benchmark names consistent
- Divide benchmark into two "groups" preffered/non-preffered

https://github.com/OpenSCAP/scap-workbench/issues/28

---

include/OscapScannerBase.h
include/Scanner.h
src/MainWindow.cpp
src/OscapScannerBase.cpp
src/Scanner.cpp
ui/MainWindow.ui

I've add support for --fetch-remote-resources to scap-workbench

Add support for fetch remote resources

---

include/MainWindow.h
src/MainWindow.cpp

https://github.com/OpenSCAP/scap-workbench/issues/25

Non intuitive "Close currently opened file" dialog text

---

include/APIHelpers.h
include/DiagnosticsDialog.h
src/APIHelpers.cpp
src/DiagnosticsDialog.cpp
src/MainWindow.cpp
src/ScanningSession.cpp

Show LibXML errors in Diagnostics Dialog

---

scap-workbench.wxs.in

I have created PR to notice you about changes
- `Advertise="no"` - I got errors with "yes"
- Added references to dlls
- Updated ssg files
- commented out `Directory Id="TRANSLATIONS" Name="translations"` There was only some dummy file, we can uncomment it in future

New wxs file after 1.1.2

---

src/Application.cpp

Arguments -v and --version prints the version of SCAP Workbench,
and arguments -h and --help prints the usage of SCAP Workbench.

RHBZ#1368527 Add support for --version and --help

---

include/SSGIntegrationDialog.h
src/Application.cpp
src/MainWindow.cpp
src/SSGIntegrationDialog.cpp
ui/SSGIntegrationDialog.ui

These changes attempt to improve UX of SSGIntegrationDialog.
- the button list has been replaced by a combo box,
- Instructions in the dialog have changed,
- and workflow of window closing have changed, for example closing SSGIntegrationDialog at startup of application closes workbench.

Improve SSGIntegrationDialog UX

---

src/TailoringWindow.cpp
ui/TailorProfileDialog.ui
ui/TailoringWindow.ui

Some improvements in the screens and message boxes used during the tailoring of a profile.

Improve tailoring UX part 1

---

src/TailoringWindow.cpp

Present the title of dialog according to the action being performed

Update title of discard change window accordingly

---

include/RemoteMachineComboBox.h
src/RemoteMachineComboBox.cpp
src/ResultViewer.cpp
ui/MainWindow.ui
ui/RemoteMachineComboBox.ui
ui/ResultViewer.ui

- Added mnemonics to save results format options
- Added mnemonics to options in menu
- Added save shortcut description into save results button tooltip
- Added labels to remote machine related fields
- Switched recent hosts button menu for a combo box

Improve some more UX in main window

---

src/MainWindow.cpp

Links in the description were made clickable.

Improve UX of about window

---

src/OscapScannerRemoteSsh.cpp

Check if oscap is available in remote machine before checking capabilities.
RHBZ#1368463

Fix scan capabilities query

---

ui/RemoteMachineComboBox.ui

- Add minimum size to recent remote machine history list and user & host line edit
- Add maximum size to recent remote machine history list
- Changed size policy of recent remote machine history list and user & host line edit to "expanding"

Improve UX of recent remote machine history list

---

src/APIHelpers.cpp
src/TailoringDockWidgets.cpp
ui/ProfilePropertiesDockWidget.ui

Fix garbled XHTML formatted profile description

---

src/RemoteMachineComboBox.cpp
src/RuleResultsTree.cpp
ui/MainWindow.ui
ui/SSGIntegrationDialog.ui

These two commits fixes the tab order in MainWindow and the default button in SSG Integration Dialog respectively.

MainWindow tab order and SSG Dialog default button

---

ui/XCCDFItemPropertiesDockWidget.ui

Fixes scrollbar style in tailoring screen

---

include/TailorProfileDialog.h
src/MainWindow.cpp
src/TailorProfileDialog.cpp

Validates custom profile id on-the-fly

---

src/MainWindow.cpp
src/TailoringWindow.cpp

Fixes memory leak as TailoringScreen is never deleted

---

src/TailoringWindow.cpp

Fixes the focus in tailoring window when (un)checking checkboxes

---

include/MainWindow.h
src/Application.cpp
src/MainWindow.cpp

This helps with QA and automation.

Support opening a tailoring file directly from the CLI

---

doc/user_manual.adoc

Separate PR against v1-1 as requested by @mpreisler.

Fix id reuse in user documentation

---

CMakeLists.txt
include/Application.h
include/ProcessHelpers.h
include/TailoringWindow.h
src/OscapScannerBase.cpp
src/OscapScannerRemoteSsh.cpp
src/ProcessHelpers.cpp
src/RemediationRoleSaver.cpp
src/SaveAsRPMDialog.cpp
src/TailoringWindow.cpp

A perfectly clean build! Absolutely no warnings or errors during build.

-Werror -Wall -Wextra

---

src/MainWindow.cpp

Closes: #169 
Also clarifies that closing the file will lose the tailoring.

Prevent application from closing when user cancels file selection

---

include/TailoringWindow.h
src/TailoringWindow.cpp

Select All Button for Tailoring

---

include/MainWindow.h
include/RemediationRoleSaver.h
include/RemoteMachineComboBox.h
include/TailorProfileDialog.h
include/TailoringUndoCommands.h
include/TailoringWindow.h
src/APIHelpers.cpp
src/DiagnosticsDialog.cpp
src/MainWindow.cpp
src/RemediationRoleSaver.cpp
src/TailoringUndoCommands.cpp
src/TailoringWindow.cpp

Paying penance for introducing one in #173 / ae8e3b570e411f494d478acc78705ce66ee7aedf, this fixes a few minor style nits in the master branch.
- pointers
- references
- curly braces
- whitespace
This targets the v1-1 branch and doesn't fix issues introduced in master since.

Style nits v1 1

---

src/Application.cpp
src/OscapScannerRemoteSsh.cpp

Paying penance for introducing one in #173 / ae8e3b570e411f494d478acc78705ce66ee7aedf, this fixes the remaining style nitpicks in master.

Style nits

---

.travis.yml

- Build DMG files using Travis

Add TRAVIS CI for OSX DMG BUILDS

---

man/scap-workbench.8

I have reviewed and updated the man page.

Update man page

---

README.md

Add a section to show on how to use a locally openscap build for this project construction.

Improve custom build documentation.

---

src/OscapScannerRemoteSsh.cpp

Just fixed a grammatical error

Grammatical errors

---

.travis.yml
build-for-osx.sh

[v1-1] Remove library so versioning for OSX builds

---

.travis.yml

Fixes error in Travis build for MacOS due to outdated xcode version

Remove old xcode

---

src/APIHelpers.cpp
src/DiagnosticsDialog.cpp
src/MainWindow.cpp
src/OscapScannerBase.cpp
src/TailoringWindow.cpp

Updates deprecated QT4 code to QT5 which fixes build failures related to deprecated QT components.

Remove deprecated or obsolete QT4 code

---

src/TailoringWindow.cpp

It will display first groups, then values, and then rules.
Each part will be sorted alphabetically according to items titles.
Sorting improves orientation in large groups, eg. SELinux group.
Fixes: RHBZ#1798739

Sort items in Tailoring window

---

doc/user_manual.adoc

This issue has been fixed by 69e988df963cb184062814e75c737fe080f303df.

Remove known issue

---

CMakeLists.txt
doc/user_manual.adoc
src/RemediationRoleSaver.cpp
ui/MainWindow.ui
ui/ResultViewer.ui

Fix terminology

---

doc/user_manual.adoc

Changes:
* Update manual with how to obtain content from upstream source
* Remove obsoleted sources of SCAP content from the manual

Update user manual
