man/scap-workbench.8

The manpage has some minor bugs:
* Fix manpage title (name), so the whatis command work properly.
* Fix hyphen where a minus sign was intended

fix two minor bugs in scap-workbench.8 manpage

---

scap-workbench-oscap.sh
scap-workbench-pkexec-oscap.sh

Bash scripts don't contain quotes where necessary - it cause problems with spaces in path, etc..
https://github.com/OpenSCAP/scap-workbench/issues/33

bash: fix quotes

---

src/DiagnosticsDialog.cpp

Add padding to diagnostics output cell
Before
--------
after

Add padding to cell of Diagnostics output

---

src/ProcessHelpers.cpp

Steps to reproduce:
- select remote scan (Linux->Linux) (you can select your localhost)
- scan
- show report -> You will see 'Â' in front of addresses (and in some other parts of document)
@msrubar found this bug

Fix strange characters in report after remote scan

---

src/TailoringWindow.cpp

It is the most clean & working solution I have found.
- Settings of `setForeground()` was very slow from some reason (https://bugreports.qt.io/browse/QTBUG-10015) and `setUpdatesEnabled();` didn't help
- Set item temporary to "enabled" worked only sometimes
https://github.com/OpenSCAP/scap-workbench/issues/24

Fix search of disabled items

---

src/TailoringDockWidgets.cpp

https://github.com/OpenSCAP/scap-workbench/issues/67
According to SSG, it use `prohibitChanges` instead of `interactive`
```
<Value id="xccdf_org.ssgproject.content_value_function_fix_audit_syscall_rule" hidden="true" prohibitChanges="true" operator="equals" type="string">
```
Do you have better idea how to visually show "changes prohibited"? (otherwise it should be ready to merge)

Don't allow edit values with changes-prohibited

---

include/Application.h
include/MainWindow.h
src/Application.cpp
src/MainWindow.cpp

Arguments -v and --version prints the version of SCAP Workbench,
and arguments -h and --help prints the usage of SCAP Workbench.
This is the same funcionality added  by
commit 9d821197d5c13e058dbdc5b8a6a03839e5817e6a, but not
using QCommandLineParser, which is only available in Qt5.

RHBZ#1368527 Add support for --version and --help

---

src/ScanningSession.cpp

Title and description of tailored profile now overrides the title and
description of parent's profile.
Related to RHBZ#1320194.

Title and description of tailored profile override

---

include/OscapScannerBase.h
include/ScanningSession.h
src/MainWindow.cpp
src/OscapScannerBase.cpp
src/OscapScannerLocal.cpp
src/OscapScannerRemoteSsh.cpp
src/ScanningSession.cpp

RHBZ#1368516
Provide actual file path of tailoring file when using dry run feature.
If tailoring is not saved, a temporary tailoring path is provided.
Also, provide paths with white spaces protected by double quotes.

Fix tailoring file path of dry run

---

include/OscapScannerBase.h
src/OscapScannerBase.cpp

Fix handling of multiple warning/error messages.
And replace messages received from oscap for meaningful messages to scap-workbench user.
Relies on https://github.com/OpenSCAP/openscap/pull/540
RHBZ#1367923

V1-1 fetch remote resources warning

---

src/OscapScannerBase.cpp

When fetching remote content, openscap will inform the scap-workbench
about resources being downloaded. The colon in the http URL of the
resource was being removed

Do not discard colon when reading dowload url

---

src/MainWindow.cpp

When users starts a dry run scan they should only see the dialog with
the command that would be performed.
RHBZ#1385549

Do not show results panel when dry running

---

CMakeLists.txt
doc/user_manual.adoc
src/OscapScannerBase.cpp

These changes makes workbench handle nicely a --fetch-remote-resources
warning message received through stdout.
This fix the use case when SCAP Workbench is running a scan in a machine 
with openscap prior to version 1.2.11.
This also removes the dependency over OpenSCAP 1.2.11 at compile time.

Fix --fetch-remote-resources warning with older openscap

---

src/OscapScannerLocal.cpp
src/OscapScannerRemoteSsh.cpp

Check capabilities of oscap by checking its version with
command `oscap -V`

Check capabilities of oscap with propper arguments

---

CMakeLists.txt
cmake/MacOSXBundleInfo.plist.in

Use a template to generate Info.plist with high-dpi capability enabled,
this is controled by `NSPrincipalClass` key.

Enable High DPI mode in MacOSX builds

---

ui/MainWindow.ui
ui/RemoteMachineComboBox.ui

The checkboxes at the botton of MainWindow are varying in size depending
on the platform and screen resolution.
Removing the fixed size allows these elements' sizes to float.
Fixes #101.

Remove fixed sizes of checkboxes and Port label

---

src/OscapScannerBase.cpp

Better document why we keep colon when reading stdout from openscap
and reading status is RS_READING_DOWNLOAD_FILE.

Comment why keep colon when reading download file

---

include/RemoteMachineComboBox.h
src/RemoteMachineComboBox.cpp

When the scan is started, the current host, port and the index of "Recent" combobox are reset.

Fixes GitHub issue #109

---

include/TailoringWindow.h
src/TailoringUndoCommands.cpp
src/TailoringWindow.cpp

Implements Tri-State checkboxes on Tailoring screen.

---

src/OscapScannerBase.cpp

Oscap used to send this message through stdout. When it changed to stderr workbench was not updated.

Reads "Downloading ..." message from stderr

---

ui/MainWindow.ui

Because of the TabFocus, clicks were not reaching the "User and host" field.

Fixes the focus of remote machine section

---

scap-workbench-oscap.sh
src/OscapScannerLocal.cpp

The cancel process kills the top most pkexec script, the oscap script notices it and try to send a SIGINT to the oscap tool, however, because of the SIGNAL trap and because SIGINT would never reach the oscap tool (even without the trap) everything keeps running.
Reference from bash manpage:
Non-builtin commands run by bash have signal handlers set to the values inherited by the shell from its parent. When job control is not in effect, asynchronous commands ignore SIGINT and SIGQUIT in addition to these inherited handlers.
Fixes #71

Fixes Cancel process

---

src/TailoringUndoCommands.cpp

Capitalizes "Set Value" undo message to make it consistent with other messages

Capitalizes "Set Value" undo message

---

src/TailoringWindow.cpp

There seems to be a bug in Qt (MacOS implementation) when it tries to calculate geometry/draw tri-state checkboxes that makes it spend much more time than usual.
This commit changes the traversal of the tree from preorder to postorder so that we set the items as expanded while they are still invisible, thus avoiding the geometry calculation and drawing. Only when the top-most item is expanded that all items are drawed, once.

Fixes the long time to open TailoringWindow in MacOS

---

include/Application.h
src/Application.cpp

If a file is passed as argument, it is loaded at the end of processCLI function, before the skip-valid option is set to the mainWindow.

Evaluates --skip-valid argument before loading file passed as argument

---

README.md

Fedora hosted is retired and their links don't work anymore.

Fix home page and user manual links

---

include/OscapScannerRemoteSsh.h
src/OscapScannerRemoteSsh.cpp
src/RemoteMachineComboBox.cpp

60000 is a valid port but can't be represented via just "short".
Fixes #140

Port needs to be unsigned short, otherwise we run risks of overflow

---

include/MainWindow.h
include/RemediationRoleSaver.h
src/MainWindow.cpp
src/RemediationRoleSaver.cpp
ui/MainWindow.ui

Before this PR, S-W was able to remediate on the fly or remediate after the check using `oscap`.
This PR aims to enable users to control the remediation by giving them access to remediation scripts (that they can edit and execute by themselves).
EDIT by @mpreisler: Let's only do generate from profiles here and generate from results can be in a separate PR.

Generate bash and ansible remediation roles from profiles

---

README.md

As mentioned recently on the mailing list:
> I've compiled openscap and the SSG locally and they work great. I'd like to try scap-workbench but cmake complains "No package 'libopenscap' found" despite having run "make install" on openscap.
Openscap comes with a `libopenscap.pc` file, but `pkg-config` can't find it. The fix is simple and included here in the README.

pkg-config path needed if openscap is compiled locally

---

include/DiagnosticsDialog.h
src/DiagnosticsDialog.cpp
ui/DiagnosticsDialog.ui

The code modification is quite trivial.
The button is apart from the other buttons, so the user is unlikely to click it by mistake.

Added possibility to clear diagnostics dialog.

---

doc/user_manual.adoc

This PR aims to document the newly-introduced possibility of saving remediation roles to the disc.
Export of result-based remediation roles from tailored profiles is partially broken, so a workaround has been provided.

Update user manual with the remediation role export feature

---

README.md

Master branch requires `qt5-devel` versus `qt-devel` package to be installed; this reflects that.

Reflect qt5-devel dependency

---

ui/TailoringWindow.ui

It is a stray line in the tailoring window. (@mpreisler says that it was probably left over from when the delete button was moved left).

Remove stray line in tailoring window

---

README.md

Required for remote ssh scanning.

Add openssh-askpass as a required dependency

---

include/MainWindow.h
include/ScanningSession.h
src/MainWindow.cpp
src/ScanningSession.cpp
src/TemporaryDir.cpp
ui/MainWindow.ui

- Implements copying input + dependencies to a temporary directory
- Adds a reload opened content button to the UI (under File)
- Opens an information dialog when the file changes on disk (once)

Better UX around opened content

---

scap-workbench-oscap.sh
scap-workbench-pkexec-oscap.sh

If an admin relaxes the required polkit authentication for running
scap-workbench-oscap.sh from auth_admin to auth_self or yes, then the
current implementation of the wrapper script allows for a local root
exploit.
A command line like this would overwrite /etc/shadow with a file owned
by the non-privileged user:
pkexec --disable-internal-agent /usr/lib64/scap-workbench/scap-workbench-oscap.sh 1000 100 \
xccdf eval --profile Default --oval-results --results /etc/shadow \
--results-arf /tmp/scap.results.arf --report /tmp/scap.report \
--progress /usr/share/openscap/scap-yast2sec-xccdf.xml
The copying of the target files needs to be done in the context of the
unprivileged user to prevent any symlink attacks or maliciously
specified paths. This is done by using sudo as a frontend to cp.
Also …

pkexec: avoid potential local root exploit by using PKEXEC_UID and sudo

---

src/OscapCapabilities.cpp

Previously we only supported versions such as 1.2.3, now we also support
1.2.3_alpha4.

Support oscap version suffix when scanning remote

---

src/SSGIntegrationDialog.cpp

Add OL7 content to SSG integration dialog
- Built scap-workbench package on top of master and installed on OL7
- Checked OL7 content available for selection and loads expected profiles
I couldn't find target branch policy for this merge, v1-2 selected by default. OL7.5 now uses scap-workbench-1.1.6 while it could be considered next update might switch to v1-2.  If possible and makes sense please merge this change in both v1-1 and v1-2 branches. Let me know if any change or additional PR required.
Signed-off-by: Ilya Okomin <ilya.okomin@oracle.com>

Add OL7 support to SSGIntegrationDialog

---

scap-workbench-oscap.sh

This patch addresses the follwong part of messages chunk. Even if it
says that "oscap" process has written the content, it's the wrapper
script in fact.
```
14:34:53 | error    | The 'oscap' process has written the following
content to stderr:
chown: cannot access '/tmp/SCAP': No such file or directory
14:34:53 | error    | The 'oscap' process has written the following
content to stderr:
chown: cannot access 'Workbench.h22666': No such file or directory
14:34:53 | error    | The 'oscap' process has written the following
content to stderr:
chown: cannot access '/tmp/SCAP': No such file or directory
14:34:53 | error    | The 'oscap' process has written the following
content to stderr:
chown: cannot access 'Workbench.M22666': No such file or directory
14:34:53 | error    | The 'oscap' …
```

Fix SCAP Workbench errors shown in Diagnostics Windows

---

ui/RuleResultItem.ui
ui/RuleResultsTree.ui

- Sets the Rule title and description font color to black. The font became hard to read when using dark themes in Gnome

[v1-2] Fix results font color

---

src/TailoringDockWidgets.cpp

The previous message suggested that the value is not used anywhere, but in fact the input data only includes checks.

Make the message concerning unused values in a rule precise.

---

ui/SSGIntegrationDialog.ui

Before, the dialog/label size was given by static values. This PR makes the dialog to resize depending on the text length, which should be more robust.
- Made the label height auto-adjustable - see https://stackoverflow.com/a/19294869
- Increased horizontal spacing between logo / label
- Removed a "widget" that isn't used, and messed up the layout
- Decreased the default dialog height, that acts as a minimal height.
Fixes: rhbz#1743713

Fixed integration dialog sizing

---

include/RemediationRoleSaver.h
include/ResultViewer.h
src/RemediationRoleSaver.cpp
src/ResultViewer.cpp

Users can generate remediation script from scan results
of a tailored profile.
Unfortunately, the current design of SCAP Workbench doesn't allow
a clear way of doing this. The scan is run in a separated oscap
process. SCAP Workbench doesn't have access to oscap internal
xccdf_session which creates the ARF. It can't obtain the Tailoring
component reference ID.
Instead, we will save the tailoring document to a temporary file
and use the temporary file when generating the remediation.
Resolves: RHBZ#1640715

Generate result-based remediation from tailored profile

---

src/SaveAsRPMDialog.cpp
src/TailoringWindow.cpp

This allows us to prevent fatal deprecation warnings from qt 5.13 to 5.14. This is also needed to support new CI pipelines that will be using the latest qt5.14.2+.

Use QT provided macro function to version check - deprecation errors

---

CMakeLists.txt

Can't find openscap library since post macOS 10.13 the standard path has been changed. This fix will use the full path to declare the location of the openscap library

Fix CMakeLists OSX build issue

---

README.md

qt5-devel is only a meta package. The real dependencies are qt5-qtbase-devel and qt5-qtxmlpatterns-devel. qt5-devel is
removed in Fedora 33. See https://lists.fedoraproject.org/archives/list/devel@lists.fedoraproject.org/message/WO625MVYEAAJNHNRLEEJDVZTIWMQOBRR/

Update list of required packages

---

src/OscapCapabilities.cpp
src/RPMOpenHelper.cpp

Starting from Qt 5.15, the enum QString::SplitBehavior is obsolete
and Qt::SplitBehavior should be used instead.
See:
https://doc.qt.io/qt-5.15/qstring-obsolete.html#SplitBehavior-enum
https://doc.qt.io/qt-5/qt.html#SplitBehaviorFlags-enum

Replace obsolete QString::SkipEmptyParts

---

src/Application.cpp

The org domain messes up the app title in the Gnome top bar. That doesn't happen on RHEL<=8, but it occurs on Fedora>=32. Other QT apps s.a. Wireshark and QT Creator don't specify the domain, so I think that the domain is not meant to be used by desktop applications, although it is not documented in this way.
Also, a domain is not the same thing as website URL, so I have changed that invocation as well. As a result, the app title was messed up a bit less, but it was still messed up.

Removed the app org domain definition.

---

include/OscapScannerBase.h
src/OscapScannerBase.cpp

This PR refactors oscap message handling - it preserves the current functionality, while it improves handling of some errors and warnings that the scanner can produce.
- Better detection of errors and warnings using leading `E:` and `W:` that oscap emits.
- Possibility to expand the message filtering using inheritance.

Refactored handling of scanner messages

---

doc/user_manual.adoc
include/OscapScannerRemoteSsh.h
include/RemoteMachineComboBox.h
src/MainWindow.cpp
src/OscapScannerRemoteSsh.cpp
src/RemoteMachineComboBox.cpp
ui/RemoteMachineComboBox.ui

- The remote scanning dialog got a "user is sudoer" checkbox.
- Dry run can make use of sudo in connection with `oscap-ssh`.
- The scanning procedure uses sudo invocation as part of the `ssh` command.
This PR depends on #271 as it makes use of advanced message filtering.
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1877522

Implement possibility to scan by sudoers.

---

src/MainWindow.cpp

Pulled from scap-workbench-1.2.1-7 in Fedora Rawhide.
`Signed-off-by: Alexander Scheel <alex.scheel@canonical.com>`

Use reference to avoid range-loop-construct diagnostic

---

src/ResultViewer.cpp

With the async behavior of Scanner (and its interactions in MainWindow),
it isn't obvious that Session can't be non-`NULL` here. Hence it is
probably better to move the session use into the if-guard.
Resolves: #262
`Signed-off-by: Alexander Scheel <alexander.m.scheel@gmail.com>`
---
Looks like @mpreisler originally wrote the if-guard but didn't mention why it was necessary either :-)

Fix potential NULL pointer dereference

---

.github/workflows/main.yml
.github/workflows/ubuntu.yml
README.md

`Signed-off-by: Alexander Scheel <alex.scheel@canonical.com>`
---
Starting slow again :-) 
Do we want to drop the `master` branch and recreate it from current `v1-2` branch (or later create a `v1-3` branch instead)?
I haven't yet checked with the current Debian maintainers to see if they're still interested in packaging `scap-workbench`. It was last present in Buster, at an earlier v1.1 version. That means it was last in 18.04 and hasn't been present since.
Is anyone here in contact with them by any chance?

Add Ubuntu dependency instructions

---

CMakeLists.txt

See: https://fedoraproject.org/wiki/Changes/Broken_RPATH_will_fail_rpmbuild
Similar to: https://github.com/OpenSCAP/openscap/pull/1765

Do not set rpath
